2024-08-22 21:38:54 [scrapy.utils.log] INFO: Scrapy 2.11.1 started (bot: crawl_gmarket)
2024-08-22 21:38:54 [scrapy.utils.log] INFO: Versions: lxml 5.2.1.0, libxml2 2.12.6, cssselect 1.2.0, parsel 1.9.1, w3lib 2.1.2, Twisted 24.3.0, Python 3.11.7 (main, Dec  9 2023, 16:56:39) [Clang 15.0.0 (clang-1500.0.40.1)], pyOpenSSL 24.1.0 (OpenSSL 3.2.1 30 Jan 2024), cryptography 42.0.7, Platform macOS-14.5-arm64-arm-64bit
2024-08-22 21:38:55 [twisted] CRITICAL: Unhandled error in Deferred:
2024-08-22 21:38:55 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/query.py", line 513, in _udp_recv
    return sock.recvfrom(max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/twisted/internet/defer.py", line 2003, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/scrapy/crawler.py", line 155, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/scrapy/crawler.py", line 169, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/scrapy/spiders/__init__.py", line 59, in from_crawler
    spider = cls(*args, **kwargs)
  File "/Users/gu/Dev/Project/OpenSW-Contest/test-space/crawl_gmarket/crawl_gmarket/spiders/gmarket.py", line 29, in __init__
    client = MongoClient(mongo_uri)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 774, in __init__
    res = uri_parser.parse_uri(
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/pymongo/uri_parser.py", line 542, in parse_uri
    nodes = dns_resolver.get_hosts()
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 140, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 120, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 106, in _resolve_uri
    results = _resolve(
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 52, in _resolve
    return resolver.resolve(*args, **kwargs)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/resolver.py", line 1565, in resolve
    return get_default_resolver().resolve(
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/resolver.py", line 1323, in resolve
    response = nameserver.query(
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/nameserver.py", line 108, in query
    response = dns.query.udp(
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/query.py", line 735, in udp
    (r, received_time) = receive_udp(
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/query.py", line 626, in receive_udp
    (wire, from_address) = _udp_recv(sock, 65535, expiration)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/query.py", line 515, in _udp_recv
    _wait_for_readable(sock, expiration)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/query.py", line 259, in _wait_for_readable
    _wait_for(s, True, False, True, expiration)
  File "/Users/gu/.pyenv/versions/dsenv/lib/python3.11/site-packages/dns/query.py", line 234, in _wait_for
    if not sel.select(timeout):
  File "/Users/gu/.pyenv/versions/3.11.7/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
